CREATE TABLE HIGHSCORE(
       autokey   INT NOT NULL PRIMARY KEY
       		    GENERATED ALWAYS AS IDENTITY
		       (START WITH 1, INCREMENT BY 1),
	score INTEGER NOT NULL,
	level  VARCHAR(128) NOT NULL
)